name: saltstack-amavis-formula
source: https://github.com/bechtoldt/saltstack-amavis-formula
summary: Salt Stack Formula to set up and configure Amavis (amavisd-new), a high-performance interface between mailer (MTA) and content checkers
todo:
  - add instructions how to use formhelper, add information about it in the formula-docs (dependency), show up alternative?
  - 'table/ matrix: os/salt compatibility (dedicated file)'
  - add list of available states
  - add tests
